name: tele_catcher
description: Catch your errors and send it to telegram
version: 0.0.8
homepage: https://github.com/alejandrogiubel/tele_catcher

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  teledart: ^0.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
