name: tele_catcher
description: Catch your errors and send it to telegram
version: 1.3.0
homepage: https://github.com/alejandrogiubel/tele_catcher

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  package_info_plus: ^8.3.1
  teledart: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
